[build]
  command = "npm run build"
  publish = ".next"
  
[template.environment]
  NOTION_TOKEN = "Set notion token"
  DATABASE_ID = "Set the database ID"
  CLIENT_PROJECTS_DATABASE_ID = "Set the database ID"
  SIDE_PROJECTS_DATABASE_ID = "Set the database ID"